"""simplified client model

Revision ID: f487b66bcfc3
Revises: 20fd910473b7
Create Date: 2025-10-20 15:50:18.039551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f487b66bcfc3'
down_revision: Union[str, Sequence[str], None] = '20fd910473b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'company')
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
